"""
STEP 4 — EXPORT FOR ANDROID
=============================
Copies model.tflite, scaler.json, and labels.json into the
React Native mobile app's assets folder.

Also generates:
  • malayalamMap.ts   — sign → Malayalam word mapping
  • datasetConfig.ts  — class list for the app

USAGE
  python step4_export_android.py
  python step4_export_android.py --app-dir path/to/mobile-app
"""

import argparse
import json
import os
import shutil
from pathlib import Path

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────
# Artifacts produced by step2_train.py
MODEL_TFLITE = Path("model.tflite")
SCALER_JSON  = Path("scaler.json")
LABELS_JSON  = Path("labels.json")

# React Native app paths (adjust if your structure differs)
DEFAULT_APP_DIR     = Path("mobile-app")
APP_MODEL_ASSETS    = DEFAULT_APP_DIR / "assets" / "model"
APP_CONSTANTS_DIR   = DEFAULT_APP_DIR / "src" / "constants"

# Malayalam word defaults — extend as you add more signs
MALAYALAM_DEFAULTS: dict[str, str] = {
    "Hello":  "നമസ്കാരം",
    "Thanks": "നന്ദി",
    "Help":   "സഹായം",
    "Water":  "വെള്ളം",
    "Food":   "ഭക്ഷണം",
    "Happy":  "സന്തോഷം",
    "Sorry":  "ക്ഷമിക്കണം",
    "I":      "ഞാൻ",
    "You":    "നീ",
    # --- extended vocabulary ---
    "They":     "അവർ",
    "Man":      "മനുഷ്യൻ",
    "Woman":    "സ്ത്രീ",
    "Boy":      "ആൺകുട്ടി",
    "Girl":     "പെൺകുട്ടി",
    "Mother":   "അമ്മ",
    "Father":   "അച്ഛൻ",
    "Friend":   "സുഹൃത്ത്",
    "Baby":     "കുഞ്ഞ്",
    "Day":      "ദിവസം",
    "Night":    "രാത്രി",
    "Morning":  "രാവിലെ",
    "Today":    "ഇന്ന്",
    "Tomorrow": "നാളെ",
    "House":    "വീട്",
    "School":   "സ്കൂൾ",
    "Tree":     "മരം",
    "Dog":      "നായ",
    "Cat":      "പൂച്ച",
    "Go":       "പോകൂ",
    "Come":     "വരൂ",
    "See":      "കാണൂ",
    "Look":     "നോക്കൂ",
    "Eat":      "കഴിക്കൂ",
    "Drink":    "കുടിക്കൂ",
    "Sleep":    "ഉറങ്ങൂ",
    "Wake":     "എഴുന്നേൽക്കൂ",
    "Work":     "ജോലി",
    "Play":     "കളിക്കൂ",
    "Walk":     "നടക്കൂ",
    "Run":      "ഓടൂ",
    "Give":     "തരൂ",
    "Want":     "വേണം",
    "Stop":     "നിർത്തൂ",
    "Sad":      "ദുഃഖം",
    "Angry":    "ദേഷ്യം",
    "Scared":   "ഭയം",
    "Good":     "നല്ലത്",
    "Bad":      "മോശം",
    "Big":      "വലിയ",
    "Small":    "ചെറിയ",
    "Hot":      "ചൂട്",
    "Cold":     "തണുപ്പ്",
    "Beautiful":"സുന്ദരം",
    "Need":     "ആവശ്യം",
    "Fine":     "ഭേദം",
    # newly requested vocabulary
    "Take":     "എടുക്കൂ",
    "Lake":     "തടാകം",
    "Fish":     "മത്സ്യം",
}

# Common phrase combinations → natural Malayalam sentence
PHRASE_MAP: dict[str, str] = {
    "I|Happy":       "ഞാൻ സന്തോഷത്തിലാണ്.",
    "You|Happy":     "നീ സന്തോഷത്തിലാണ്.",
    "I|Sorry":       "ഞാൻ ക്ഷമ ചോദിക്കുന്നു.",
    "You|Sorry":     "നീ ക്ഷമ ചോദിക്കുന്നു.",
    "I|Need|Water":  "എനിക്ക് വെള്ളം വേണം.",
    "I|Need|Food":   "എനിക്ക് ഭക്ഷണം വേണം.",
    "I|Want|Help":   "എനിക്ക് സഹായം വേണം.",
    "Hello|You":     "നിനക്ക് നമസ്കാരം.",
    "You|Need|Help": "നിനക്ക് സഹായം ആവശ്യമുണ്ട്.",
    "I|Good":        "ഞാൻ നന്നായിരിക്കുന്നു.",
    "I|Fine":        "ഞാൻ ഭേദമായിരിക്കുന്നു.",
}
# ─────────────────────────────────────────────


def load_labels(labels_path: Path) -> list[str]:
    if not labels_path.exists():
        raise FileNotFoundError(
            f"{labels_path} not found. Run step2_train.py first."
        )
    with open(labels_path, encoding="utf-8") as f:
        return json.load(f)


def copy_model_assets(
    labels: list[str],
    app_model_dir: Path,
) -> None:
    app_model_dir.mkdir(parents=True, exist_ok=True)
    files = [MODEL_TFLITE, SCALER_JSON, LABELS_JSON]
    print(f"\n📦  Copying model assets → {app_model_dir}/")
    for src in files:
        if not src.exists():
            print(f"  ⚠️  Not found: {src}  (run step2_train.py first)")
            continue
        dst = app_model_dir / src.name
        shutil.copy2(src, dst)
        size_kb = dst.stat().st_size / 1024
        print(f"  ✅  {src.name:<25s} {size_kb:.0f} KB → {dst}")


def write_dataset_config(labels: list[str], out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "datasetConfig.ts"
    content = "\n".join([
        "// AUTO-GENERATED by step4_export_android.py — do not edit manually",
        "",
        "export const DATASET_LABELS: string[] = " + json.dumps(labels, ensure_ascii=False) + ";",
        "",
        "export const SEQUENCE_LENGTH = 30;",
        "export const N_FEATURES = 225;",
        "",
        "export const INFERENCE_THRESHOLD = 0.85;",
        "",
    ])
    path.write_text(content, encoding="utf-8")
    print(f"  ✅  {path}")


def write_malayalam_map(labels: list[str], out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "malayalamMap.ts"

    # Build word map for current labels only
    word_map = {label: MALAYALAM_DEFAULTS.get(label, label) for label in labels}

    # Build phrase map for phrases where all tokens are in labels
    phrase_map = {
        key: val
        for key, val in PHRASE_MAP.items()
        if all(token in labels for token in key.split("|"))
    }

    lines: list[str] = [
        "// AUTO-GENERATED by step4_export_android.py — do not edit manually",
        "",
        "export const MALAYALAM_WORD_MAP: Record<string, string> = {",
    ]
    for label in labels:
        ml = word_map[label]
        lines.append(f"  {json.dumps(label)}: {json.dumps(ml, ensure_ascii=False)},")
    lines += [
        "};",
        "",
        "export const MALAYALAM_PHRASE_MAP: Record<string, string> = {",
    ]
    for key, sentence in phrase_map.items():
        lines.append(f"  {json.dumps(key)}: {json.dumps(sentence, ensure_ascii=False)},")
    lines += [
        "};",
        "",
        "// Collapse consecutive duplicate signs and strip blanks",
        "function normalizeSigns(signs: string[]): string[] {",
        "  const deduped: string[] = [];",
        "  for (const s of signs.map(x => x.trim()).filter(Boolean)) {",
        "    if (deduped[deduped.length - 1] !== s) deduped.push(s);",
        "  }",
        "  return deduped;",
        "}",
        "",
        "// Convert a sequence of detected signs to a Malayalam string",
        "export function signsToMalayalam(signs: string[]): string {",
        "  const norm = normalizeSigns(signs);",
        "  if (norm.length === 0) return '';",
        "",
        "  const phraseKey = norm.join('|');",
        "  if (MALAYALAM_PHRASE_MAP[phraseKey]) return MALAYALAM_PHRASE_MAP[phraseKey];",
        "",
        "  const words = norm.map(s => MALAYALAM_WORD_MAP[s] ?? s).join(' ');",
        "  return words.endsWith('.') || words.endsWith('।') ? words : `${words}.`;",
        "}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  ✅  {path}")


def write_tflite_helper(out_dir: Path) -> None:
    """
    Writes a TypeScript helper that shows how to:
      1. Load scaler.json
      2. Apply StandardScaler transform
      3. Run TFLite inference
    This is a reference implementation — actual TFLite calls depend on
    which React Native TFLite library your team uses.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "inferenceHelper.ts"
    content = """// AUTO-GENERATED by step4_export_android.py
// Reference implementation for TFLite inference in React Native.
// Adapt the TFLite loading to your chosen library
// (e.g. react-native-fast-tflite or a custom native module).

import scalerData from '../../assets/model/scaler.json';
import labelsData from '../../assets/model/labels.json';
import { INFERENCE_THRESHOLD, SEQUENCE_LENGTH, N_FEATURES } from '../constants/datasetConfig';

// ─── Types ───────────────────────────────────────────────────────
interface ScalerData {
  mean:  number[];
  scale: number[];
  n_features: number;
}

// ─── Constants ───────────────────────────────────────────────────
const SCALER = scalerData as ScalerData;
const LABELS = labelsData as string[];

// ─── Scaler ──────────────────────────────────────────────────────
/**
 * Apply the same StandardScaler transform used during training.
 * input:  Float32Array of length (SEQUENCE_LENGTH * N_FEATURES)
 * output: Float32Array same length, scaled
 */
export function applyScaler(flat: Float32Array): Float32Array {
  const out = new Float32Array(flat.length);
  for (let i = 0; i < flat.length; i++) {
    const featIdx = i % N_FEATURES;
    out[i] = (flat[i] - SCALER.mean[featIdx]) / SCALER.scale[featIdx];
  }
  return out;
}

// ─── Normalization ───────────────────────────────────────────────
/**
 * Wrist-relative + scale-normalized for a single hand (63 values).
 * Must match the Python normalize_hand() function exactly.
 */
export function normalizeHand(hand: Float32Array): Float32Array {
  // hand: 21 landmarks × 3 = 63 floats [x0,y0,z0, x1,y1,z1, ...]
  const pts = Array.from({ length: 21 }, (_, i) => ({
    x: hand[i * 3],
    y: hand[i * 3 + 1],
    z: hand[i * 3 + 2],
  }));

  const wrist = { ...pts[0] };
  for (const p of pts) { p.x -= wrist.x; p.y -= wrist.y; p.z -= wrist.z; }

  const p9    = pts[9];
  const scale = Math.sqrt(p9.x * p9.x + p9.y * p9.y + p9.z * p9.z);

  const out = new Float32Array(63);
  if (scale > 1e-6) {
    for (let i = 0; i < 21; i++) {
      out[i * 3]     = pts[i].x / scale;
      out[i * 3 + 1] = pts[i].y / scale;
      out[i * 3 + 2] = pts[i].z / scale;
    }
  }
  return out;
}

/**
 * Shoulder-midpoint-relative + shoulder-width-normalized for pose (99 values).
 * Must match the Python normalize_pose() function exactly.
 */
export function normalizePose(pose: Float32Array): Float32Array {
  // pose: 33 landmarks × 3 = 99 floats
  const pts = Array.from({ length: 33 }, (_, i) => ({
    x: pose[i * 3],
    y: pose[i * 3 + 1],
    z: pose[i * 3 + 2],
  }));

  const lSh = pts[11];
  const rSh = pts[12];
  const mid = { x: (lSh.x + rSh.x) / 2, y: (lSh.y + rSh.y) / 2, z: (lSh.z + rSh.z) / 2 };

  for (const p of pts) { p.x -= mid.x; p.y -= mid.y; p.z -= mid.z; }

  const dx    = lSh.x - rSh.x;
  const dy    = lSh.y - rSh.y;
  const dz    = lSh.z - rSh.z;
  const width = Math.sqrt(dx * dx + dy * dy + dz * dz);

  const out = new Float32Array(99);
  if (width > 1e-6) {
    for (let i = 0; i < 33; i++) {
      out[i * 3]     = pts[i].x / width;
      out[i * 3 + 1] = pts[i].y / width;
      out[i * 3 + 2] = pts[i].z / width;
    }
  }
  return out;
}

// ─── Inference ───────────────────────────────────────────────────
/**
 * Run inference on a (SEQUENCE_LENGTH, N_FEATURES) sequence.
 *
 * @param sequence  - flat Float32Array of length SEQUENCE_LENGTH * N_FEATURES
 * @param tfliteRun - your TFLite run function, takes (Float32Array) → Float32Array
 * @returns { label, confidence } or null if below threshold
 */
export async function predict(
  sequence: Float32Array,
  tfliteRun: (input: Float32Array) => Promise<Float32Array>,
): Promise<{ label: string; confidence: number } | null> {
  const scaled  = applyScaler(sequence);
  const outputs = await tfliteRun(scaled);

  let maxIdx  = 0;
  let maxConf = outputs[0];
  for (let i = 1; i < outputs.length; i++) {
    if (outputs[i] > maxConf) { maxConf = outputs[i]; maxIdx = i; }
  }

  if (maxConf < INFERENCE_THRESHOLD) return null;
  return { label: LABELS[maxIdx], confidence: maxConf };
}
"""
    path.write_text(content, encoding="utf-8")
    print(f"  ✅  {path}")


# ═══════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════
def main(app_dir: Path):
    print("\n" + "=" * 65)
    print("📱  ANDROID EXPORT")
    print("=" * 65)

    labels = load_labels(LABELS_JSON)
    print(f"\n    Labels : {labels}")

    app_model_dir  = app_dir / "assets" / "model"
    constants_dir  = app_dir / "src" / "constants"
    helpers_dir    = app_dir / "src" / "utils"

    copy_model_assets(labels, app_model_dir)

    print(f"\n📝  Writing TypeScript constants → {constants_dir}/")
    write_dataset_config(labels, constants_dir)
    write_malayalam_map(labels, constants_dir)

    print(f"\n📝  Writing inference helper → {helpers_dir}/")
    write_tflite_helper(helpers_dir)

    print(f"\n{'='*65}")
    print(f"✅  Export complete")
    print(f"{'='*65}")
    print(f"""
    Files to commit to your React Native repo:
      {app_model_dir}/model.tflite
      {app_model_dir}/scaler.json
      {app_model_dir}/labels.json
      {constants_dir}/datasetConfig.ts
      {constants_dir}/malayalamMap.ts
      {helpers_dir}/inferenceHelper.ts

    ⚠️  Re-run this script every time you retrain the model.
""")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export model artifacts for Android")
    parser.add_argument("--app-dir", default=str(DEFAULT_APP_DIR),
                        help="Path to React Native app root")
    args = parser.parse_args()
    main(Path(args.app_dir))
